In [1]:
import pandas as pd

In [2]:
medical_df = pd.read_csv("insurance.csv")

In [3]:
medical_df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
medical_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
medical_df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
import seaborn as sns

In [7]:
smoker_codes = {'no': 0, 'yes':1}
medical_df['smoker_codes'] = medical_df.smoker.map(smoker_codes)

In [8]:
medical_df

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smoker_codes  
0                1  
1                0  
2                0  
3                0  
4                0  
...            ...  
1333             0  
1334             0  
1335             0  
1336             0  
1337             1  

[1338 rows x 8 columns]

In [9]:
sex_codes = {'female':0, 'male': 1}
medical_df['sex_codes'] = medical_df.sex.map(sex_codes)

In [10]:
medical_df

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smoker_codes  sex_codes  
0                1          0  
1                0          1  
2                0          1  
3                0          1  
4                0          1  
...            ...        ...  
1333             0          1  
1334             0          0  
1335             0          0  
1336             0          0  
1337             1          0  

[1338 rows x 9 columns]

In [11]:
# one hot encoding
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc.fit(medical_df[['region']])
print(enc.categories_)
one_hot = enc.transform(medical_df[['region']]).toarray()
print(one_hot)

[array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [12]:
medical_df[['northeast', 'northwest', 'southeast', 'southwest']] = one_hot

In [13]:
medical_df

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      smoker_codes  sex_codes  northeast  northwest  southeast  southwest  
0                1          0        0.0        0.0        0.0        1.0  
1                0          1        0.0        0.0        1.0        0.0  
2                0          1        0.0        0.0        1.0        0.0  
3                0          1        0.0        1.0        0.0        0.0  
4                0          1        0.0        1.0        0.0        0.0  
...            ...        ...        ...        ...        ...        ...  
1333             0          1        0.0        1.0        0.0        0.0  
1334             0          0        1.0        0.0        0.0        0.0  
1335             0          0        0.0        0.0        1.0        0.0  
1336             0          0        0.0        0.0        0.0        1.0  
1337             1          0        0.0        1.0        0.0        0.0  

[1338 rows x 13 columns]

In [24]:
# scaling
from sklearn.preprocessing import StandardScaler

numeric_cols = ['age', 'bmi']
scalar = StandardScaler()
scalar.fit(medical_df[numeric_cols])

scaled_inputs = scalar.transform(medical_df[numeric_cols])
scaled_inputs

array([[-1.43876426, -0.45332   ],
       [-1.50996545,  0.5096211 ],
       [-0.79795355,  0.38330685],
       ...,
       [-1.50996545,  1.0148781 ],
       [-1.29636188, -0.79781341],
       [ 1.55168573, -0.26138796]], shape=(1338, 2))

In [25]:
# categorical or numerical col
cat_cols = ['smoker_codes', 'sex_codes', 'northeast', 'northwest', 'southeast', 'southwest']
categorical_data = medical_df[cat_cols].values
categorical_data

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.]], shape=(1338, 6))

In [26]:
import numpy as np

def rmse(target, prediction):
    return np.sqrt(np.mean(np.square(target - prediction)))

In [27]:
# model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

inputs = np.concatenate((scaled_inputs, categorical_data), axis=1)
targets = medical_df.charges

inputs_train, inputs_test, targets_train, targets_test = train_test_split(inputs, targets, test_size=0.1)

model = LinearRegression()

model.fit(inputs_train, targets_train)

prediction_test = model.predict(inputs_test)

loss = rmse(targets_test, prediction_test)
print("RMSE Loss", loss)


RMSE Loss 5171.246560082381


In [28]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math

print("R² Score:", r2_score(targets_test, prediction_test))
print("MAE:", mean_absolute_error(targets_test, prediction_test))
print("MSE:", mean_squared_error(targets_test, prediction_test))
print("Root Mean Squared Error: ",math.sqrt(mean_squared_error(targets_test, prediction_test)))

R² Score: 0.8181471553324366
MAE: 3925.418186298479
MSE: 26741790.98516386
Root Mean Squared Error:  5171.246560082381
